case = "ignore"
end-markers = "?!:."
features = "format-block-quotes,collate-link-defs,outsource-inline-links"
ignores = ""
lang = "ac"
max-width = 80
suppressions = ""
upstream-command = "prettier"
upstream = "--parser=markdown --tab-width=4"
upstream-separator = " "
